package com.zdnst.maps.group.entity;

import com.zdnst.common.persistent.db.BaseModel;

public class UrUser extends BaseModel {
	// extends BaseVO implements IDomainObject
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.account
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String account;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.nickName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String nickName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.password
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.mailBox
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String mailBox;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.mobile
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.gender
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.identityCard
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String identityCard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.birthday
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Long birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.company
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String company;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userSign
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userSign;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.province
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.city
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.county
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String county;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.address
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.registTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Long registTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.cardImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String cardImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.mobileFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String mobileFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.mailFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String mailFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.lastTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Long lastTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.ip
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.clientInfo
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String clientInfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userType
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.loginId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String loginId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.groupId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String groupId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.version
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.degree
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String degree;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.fansQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Integer fansQty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.followQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Integer followQty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.coverImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String coverImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.income
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String income;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.state
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.userFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String userFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.groupFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String groupFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.createTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Long createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.updateTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private Long updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.createUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.updateUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String updateUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ju_ur_user.delFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userId
	 * 
	 * @return the value of ju_ur_user.userId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userId
	 * 
	 * @param userId
	 *            the value for ju_ur_user.userId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.account
	 * 
	 * @return the value of ju_ur_user.account
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.account
	 * 
	 * @param account
	 *            the value for ju_ur_user.account
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.nickName
	 * 
	 * @return the value of ju_ur_user.nickName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.nickName
	 * 
	 * @param nickName
	 *            the value for ju_ur_user.nickName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.password
	 * 
	 * @return the value of ju_ur_user.password
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.password
	 * 
	 * @param password
	 *            the value for ju_ur_user.password
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userName
	 * 
	 * @return the value of ju_ur_user.userName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userName
	 * 
	 * @param userName
	 *            the value for ju_ur_user.userName
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.mailBox
	 * 
	 * @return the value of ju_ur_user.mailBox
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getMailBox() {
		return mailBox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.mailBox
	 * 
	 * @param mailBox
	 *            the value for ju_ur_user.mailBox
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setMailBox(String mailBox) {
		this.mailBox = mailBox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.mobile
	 * 
	 * @return the value of ju_ur_user.mobile
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.mobile
	 * 
	 * @param mobile
	 *            the value for ju_ur_user.mobile
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.gender
	 * 
	 * @return the value of ju_ur_user.gender
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.gender
	 * 
	 * @param gender
	 *            the value for ju_ur_user.gender
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.identityCard
	 * 
	 * @return the value of ju_ur_user.identityCard
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getIdentityCard() {
		return identityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.identityCard
	 * 
	 * @param identityCard
	 *            the value for ju_ur_user.identityCard
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.birthday
	 * 
	 * @return the value of ju_ur_user.birthday
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Long getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.birthday
	 * 
	 * @param birthday
	 *            the value for ju_ur_user.birthday
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setBirthday(Long birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.company
	 * 
	 * @return the value of ju_ur_user.company
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.company
	 * 
	 * @param company
	 *            the value for ju_ur_user.company
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userSign
	 * 
	 * @return the value of ju_ur_user.userSign
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserSign() {
		return userSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userSign
	 * 
	 * @param userSign
	 *            the value for ju_ur_user.userSign
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserSign(String userSign) {
		this.userSign = userSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.province
	 * 
	 * @return the value of ju_ur_user.province
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.province
	 * 
	 * @param province
	 *            the value for ju_ur_user.province
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.city
	 * 
	 * @return the value of ju_ur_user.city
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.city
	 * 
	 * @param city
	 *            the value for ju_ur_user.city
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.county
	 * 
	 * @return the value of ju_ur_user.county
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.county
	 * 
	 * @param county
	 *            the value for ju_ur_user.county
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCounty(String county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.address
	 * 
	 * @return the value of ju_ur_user.address
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.address
	 * 
	 * @param address
	 *            the value for ju_ur_user.address
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.registTime
	 * 
	 * @return the value of ju_ur_user.registTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Long getRegistTime() {
		return registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.registTime
	 * 
	 * @param registTime
	 *            the value for ju_ur_user.registTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setRegistTime(Long registTime) {
		this.registTime = registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userImg
	 * 
	 * @return the value of ju_ur_user.userImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserImg() {
		return userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userImg
	 * 
	 * @param userImg
	 *            the value for ju_ur_user.userImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserImg(String userImg) {
		this.userImg = userImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.cardImg
	 * 
	 * @return the value of ju_ur_user.cardImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCardImg() {
		return cardImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.cardImg
	 * 
	 * @param cardImg
	 *            the value for ju_ur_user.cardImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCardImg(String cardImg) {
		this.cardImg = cardImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.mobileFlag
	 * 
	 * @return the value of ju_ur_user.mobileFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getMobileFlag() {
		return mobileFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.mobileFlag
	 * 
	 * @param mobileFlag
	 *            the value for ju_ur_user.mobileFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setMobileFlag(String mobileFlag) {
		this.mobileFlag = mobileFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.mailFlag
	 * 
	 * @return the value of ju_ur_user.mailFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getMailFlag() {
		return mailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.mailFlag
	 * 
	 * @param mailFlag
	 *            the value for ju_ur_user.mailFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setMailFlag(String mailFlag) {
		this.mailFlag = mailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.lastTime
	 * 
	 * @return the value of ju_ur_user.lastTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Long getLastTime() {
		return lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.lastTime
	 * 
	 * @param lastTime
	 *            the value for ju_ur_user.lastTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setLastTime(Long lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.ip
	 * 
	 * @return the value of ju_ur_user.ip
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.ip
	 * 
	 * @param ip
	 *            the value for ju_ur_user.ip
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.clientInfo
	 * 
	 * @return the value of ju_ur_user.clientInfo
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getClientInfo() {
		return clientInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.clientInfo
	 * 
	 * @param clientInfo
	 *            the value for ju_ur_user.clientInfo
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setClientInfo(String clientInfo) {
		this.clientInfo = clientInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userType
	 * 
	 * @return the value of ju_ur_user.userType
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userType
	 * 
	 * @param userType
	 *            the value for ju_ur_user.userType
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.loginId
	 * 
	 * @return the value of ju_ur_user.loginId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.loginId
	 * 
	 * @param loginId
	 *            the value for ju_ur_user.loginId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.groupId
	 * 
	 * @return the value of ju_ur_user.groupId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.groupId
	 * 
	 * @param groupId
	 *            the value for ju_ur_user.groupId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.version
	 * 
	 * @return the value of ju_ur_user.version
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.version
	 * 
	 * @param version
	 *            the value for ju_ur_user.version
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.degree
	 * 
	 * @return the value of ju_ur_user.degree
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getDegree() {
		return degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.degree
	 * 
	 * @param degree
	 *            the value for ju_ur_user.degree
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setDegree(String degree) {
		this.degree = degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.fansQty
	 * 
	 * @return the value of ju_ur_user.fansQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Integer getFansQty() {
		return fansQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.fansQty
	 * 
	 * @param fansQty
	 *            the value for ju_ur_user.fansQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setFansQty(Integer fansQty) {
		this.fansQty = fansQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.followQty
	 * 
	 * @return the value of ju_ur_user.followQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Integer getFollowQty() {
		return followQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.followQty
	 * 
	 * @param followQty
	 *            the value for ju_ur_user.followQty
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setFollowQty(Integer followQty) {
		this.followQty = followQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.coverImg
	 * 
	 * @return the value of ju_ur_user.coverImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCoverImg() {
		return coverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.coverImg
	 * 
	 * @param coverImg
	 *            the value for ju_ur_user.coverImg
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCoverImg(String coverImg) {
		this.coverImg = coverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.income
	 * 
	 * @return the value of ju_ur_user.income
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getIncome() {
		return income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.income
	 * 
	 * @param income
	 *            the value for ju_ur_user.income
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setIncome(String income) {
		this.income = income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.state
	 * 
	 * @return the value of ju_ur_user.state
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.state
	 * 
	 * @param state
	 *            the value for ju_ur_user.state
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.userFlag
	 * 
	 * @return the value of ju_ur_user.userFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUserFlag() {
		return userFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.userFlag
	 * 
	 * @param userFlag
	 *            the value for ju_ur_user.userFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUserFlag(String userFlag) {
		this.userFlag = userFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.groupFlag
	 * 
	 * @return the value of ju_ur_user.groupFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getGroupFlag() {
		return groupFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.groupFlag
	 * 
	 * @param groupFlag
	 *            the value for ju_ur_user.groupFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setGroupFlag(String groupFlag) {
		this.groupFlag = groupFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.createTime
	 * 
	 * @return the value of ju_ur_user.createTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.createTime
	 * 
	 * @param createTime
	 *            the value for ju_ur_user.createTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.updateTime
	 * 
	 * @return the value of ju_ur_user.updateTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.updateTime
	 * 
	 * @param updateTime
	 *            the value for ju_ur_user.updateTime
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.createUserId
	 * 
	 * @return the value of ju_ur_user.createUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.createUserId
	 * 
	 * @param createUserId
	 *            the value for ju_ur_user.createUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.updateUserId
	 * 
	 * @return the value of ju_ur_user.updateUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.updateUserId
	 * 
	 * @param updateUserId
	 *            the value for ju_ur_user.updateUserId
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ju_ur_user.delFlag
	 * 
	 * @return the value of ju_ur_user.delFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ju_ur_user.delFlag
	 * 
	 * @param delFlag
	 *            the value for ju_ur_user.delFlag
	 * 
	 * @mbggenerated Fri Aug 29 14:49:57 CST 2014
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	public Object getId() {

		return this.userId;
	}
}